package com.compiler.parser;

public enum TokenType {
    NUMBER, WORD, TEXT,
    PRINT, IF, ELSE, FOR, WHILE, DO, BREAK, CONTINUE,
    DEF,
    PLUS, MINUS, STAR, SLASH,
    EQ, EQEQ, LT, LTEQ, GT, GTEQ, EXCLUDE, EXCLUDEEQ, BAR, BARBAR, AMP, AMPAMP,
    LPAREN, RPAREN, LBRACE, RBRACE, SEMICOLON, COMMA,
    EOF
}
